version: '3.8'

services:
  app:
    image: darti563/my-node-app:latest 
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - frontend

  proxy:
    image: nginx:latest
    ports:
      - "8080:80"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  frontend:

volumes: {}